[package]
name = "test-sdl2"
version = "0.6.0"
authors = ["SearchingFox <n3tstrang3r@yandex.ru>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
png = "0"
rand = "0"
rayon = "1"
sdl2 = "0"
rug = "1"

