[package]
name = "notes-graph"
version = "0.4.0"
edition = "2018"

[profile.release]
lto = "thin"

[dependencies]
rand = "0"
regex = "1"
bincode = "1"

[dependencies.sdl2]
version = "0"
default-features = false
features = ["ttf"]

[dependencies.sdl2-sys]
version = "0"
features = ["bundled"]
